### ISSUE TITLE
Add Feature: Graph

### ISSUE THREAD

**Issue by gabo0802** [gabo0802/UF-OneClick#65]
**Graph**

If possible, we would like to implement a graph that displays how much a user has spent each month based on the subscriptions that they own.

**Tasks**
- [x] Find a graphing library to implement this
- [x] Given the data that we have in the database, determine the parameters for the x and y axes for the graph
- [ ] Possible ways for us to customize the graph?

**Comment by valekseev03** [comment]
Parameters are the dates (month and year) for the x-axis and the total price for all subscriptions (or some other info about the subscriptions) for the y-axis
